# Generated by Django 4.2.2 on 2023-06-22 16:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Название')),
                ('content', ckeditor.fields.RichTextField()),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('visible', models.BooleanField(db_index=True, default=False, verbose_name='Видимость')),
                ('thumbnail', models.ImageField(upload_to='', verbose_name='Превью')),
            ],
            options={
                'verbose_name': 'Посты',
            },
        ),
    ]
